module "network_security_group" {
  source  = "Azure/avm-res-network-networksecuritygroup/azurerm"
  version = "0.4.0"

  location            = var.network_security_group_config.location
  name                = var.network_security_group_config.name
  resource_group_name = var.network_security_group_config.resource_group_name
  tags                = var.network_security_group_config.tags
  timeouts            = var.network_security_group_config.timeouts
  lock                = var.network_security_group_config.lock
  role_assignments    = var.network_security_group_config.role_assignments
  diagnostic_settings = var.network_security_group_config.diagnostic_settings
  enable_telemetry    = var.network_security_group_config.enable_telemetry
}
module "network_interface" {
  source  = "Azure/avm-res-network-networkinterface/azurerm"
  version = "0.1.0"

  name                                          = var.network_interface_config.name
  location                                      = var.network_interface_config.location
  resource_group_name                           = var.network_interface_config.resource_group_name
  accelerated_networking_enabled                = var.network_interface_config.accelerated_networking_enabled
  dns_servers                                   = var.network_interface_config.dns_servers
  edge_zone                                     = var.network_interface_config.edge_zone
  internal_dns_name_label                       = var.network_interface_config.internal_dns_name_label
  ip_forwarding_enabled                         = var.network_interface_config.ip_forwarding_enabled
  tags                                          = var.network_interface_config.tags
  ip_configurations                             = var.network_interface_config.ip_configurations
  load_balancer_backend_address_pool_association = var.network_interface_config.load_balancer_backend_address_pool_association
  application_gateway_backend_address_pool_association = var.network_interface_config.application_gateway_backend_address_pool_association
  application_security_group_ids                = var.network_interface_config.application_security_group_ids
  nat_rule_association                          = var.network_interface_config.nat_rule_association
  network_security_group_ids                    = var.network_interface_config.network_security_group_ids
  lock                                          = var.network_interface_config.lock
}
module "virtual_machine" {
  source  = "Azure/avm-res-azurestackhci-virtualmachineinstance/azurerm"
  version = "2.0.0"

  name                        = var.virtual_machine_config.name
  location                    = var.virtual_machine_config.location
  resource_group_name         = var.virtual_machine_config.resource_group_name
  custom_location_id          = var.virtual_machine_config.custom_location_id
  image_id                    = var.virtual_machine_config.image_id
  logical_network_id          = var.virtual_machine_config.logical_network_id
  admin_username              = var.virtual_machine_config.admin_username
  admin_password              = var.virtual_machine_config.admin_password
  memory_mb                   = var.virtual_machine_config.memory_mb
  v_cpu_count                 = var.virtual_machine_config.v_cpu_count
  dynamic_memory              = var.virtual_machine_config.dynamic_memory
  dynamic_memory_min          = var.virtual_machine_config.dynamic_memory_min
  dynamic_memory_max          = var.virtual_machine_config.dynamic_memory_max
  dynamic_memory_buffer       = var.virtual_machine_config.dynamic_memory_buffer
  secure_boot_enabled         = var.virtual_machine_config.secure_boot_enabled
  auto_upgrade_minor_version  = var.virtual_machine_config.auto_upgrade_minor_version
  enable_telemetry            = var.virtual_machine_config.enable_telemetry
  os_type                     = var.virtual_machine_config.os_type
  tags                        = var.virtual_machine_config.tags
  nic_tags                    = var.virtual_machine_config.nic_tags
  private_ip_address          = var.virtual_machine_config.private_ip_address
  domain_to_join              = var.virtual_machine_config.domain_to_join
  domain_target_ou            = var.virtual_machine_config.domain_target_ou
  domain_join_user_name       = var.virtual_machine_config.domain_join_user_name
  domain_join_password        = var.virtual_machine_config.domain_join_password
  domain_join_extension_tags  = var.virtual_machine_config.domain_join_extension_tags
  data_disk_params            = var.virtual_machine_config.data_disk_params
  managed_identities          = var.virtual_machine_config.managed_identities
  role_assignments            = var.virtual_machine_config.role_assignments
  lock                        = var.virtual_machine_config.lock
  linux_ssh_config            = var.virtual_machine_config.linux_ssh_config
  windows_ssh_config          = var.virtual_machine_config.windows_ssh_config
  http_proxy                  = var.virtual_machine_config.http_proxy
  https_proxy                 = var.virtual_machine_config.https_proxy
  no_proxy                    = var.virtual_machine_config.no_proxy
  trusted_ca                  = var.virtual_machine_config.trusted_ca
  user_storage_id             = var.virtual_machine_config.user_storage_id
  type_handler_version        = var.virtual_machine_config.type_handler_version
}
module "load_balancer" {
  source  = "Azure/avm-res-network-loadbalancer/azurerm"
  version = "0.4.0"

  name                        = var.load_balancer_config.name
  location                    = var.load_balancer_config.location
  resource_group_name         = var.load_balancer_config.resource_group_name
  edge_zone                   = var.load_balancer_config.edge_zone
  sku                         = var.load_balancer_config.sku
  sku_tier                    = var.load_balancer_config.sku_tier
  tags                        = var.load_balancer_config.tags
  frontend_ip_configurations  = var.load_balancer_config.frontend_ip_configurations
  backend_address_pools       = var.load_balancer_config.backend_address_pools
  backend_address_pool_addresses = var.load_balancer_config.backend_address_pool_addresses
  backend_address_pool_network_interfaces = var.load_balancer_config.backend_address_pool_network_interfaces
  backend_address_pool_configuration = var.load_balancer_config.backend_address_pool_configuration
  lb_probes                   = var.load_balancer_config.lb_probes
  lb_rules                    = var.load_balancer_config.lb_rules
  lb_nat_rules                = var.load_balancer_config.lb_nat_rules
  lb_outbound_rules           = var.load_balancer_config.lb_outbound_rules
  lb_nat_pools                = var.load_balancer_config.lb_nat_pools
  public_ip_address_configuration = var.load_balancer_config.public_ip_address_configuration
  frontend_subnet_resource_id = var.load_balancer_config.frontend_subnet_resource_id
  diagnostic_settings         = var.load_balancer_config.diagnostic_settings
  role_assignments            = var.load_balancer_config.role_assignments
  lock                        = var.load_balancer_config.lock
  enable_telemetry            = var.load_balancer_config.enable_telemetry
}
module "storage_account" {
  source  = "Azure/avm-res-storage-storageaccount/azurerm"
  version = "0.6.3"

  account_replication_type          = var.storage_account_config.account_replication_type
  account_tier                      = var.storage_account_config.account_tier
  location                          = var.storage_account_config.location
  name                              = var.storage_account_config.name
  resource_group_name               = var.storage_account_config.resource_group_name
  access_tier                       = var.storage_account_config.access_tier
  account_kind                      = var.storage_account_config.account_kind
  allow_nested_items_to_be_public   = var.storage_account_config.allow_nested_items_to_be_public
  allowed_copy_scope                = var.storage_account_config.allowed_copy_scope
  cross_tenant_replication_enabled  = var.storage_account_config.cross_tenant_replication_enabled
  default_to_oauth_authentication   = var.storage_account_config.default_to_oauth_authentication
  edge_zone                         = var.storage_account_config.edge_zone
  https_traffic_only_enabled        = var.storage_account_config.https_traffic_only_enabled
  infrastructure_encryption_enabled = var.storage_account_config.infrastructure_encryption_enabled
  is_hns_enabled                    = var.storage_account_config.is_hns_enabled
  large_file_share_enabled          = var.storage_account_config.large_file_share_enabled
  min_tls_version                   = var.storage_account_config.min_tls_version
  nfsv3_enabled                     = var.storage_account_config.nfsv3_enabled
  public_network_access_enabled     = var.storage_account_config.public_network_access_enabled
  queue_encryption_key_type         = var.storage_account_config.queue_encryption_key_type
  sftp_enabled                      = var.storage_account_config.sftp_enabled
  shared_access_key_enabled         = var.storage_account_config.shared_access_key_enabled
  table_encryption_key_type         = var.storage_account_config.table_encryption_key_type
  tags                              = var.storage_account_config.tags
  azure_files_authentication        = var.storage_account_config.azure_files_authentication
  blob_properties                   = var.storage_account_config.blob_properties
  custom_domain                     = var.storage_account_config.custom_domain
  managed_identities                = var.storage_account_config.managed_identities
  immutability_policy               = var.storage_account_config.immutability_policy
  network_rules                     = var.storage_account_config.network_rules
  routing                           = var.storage_account_config.routing
  sas_policy                        = var.storage_account_config.sas_policy
  share_properties                  = var.storage_account_config.share_properties
  timeouts                          = var.storage_account_config.timeouts
  customer_managed_key              = var.storage_account_config.customer_managed_key
  role_assignments                  = var.storage_account_config.role_assignments
  static_website                    = var.storage_account_config.static_website
  queue_properties                  = var.storage_account_config.queue_properties
}
module "sql_server" {
  source = "Azure/avm-res-sql-server/azurerm"
  version = "0.1.5"

  name                                         = var.sql_server_config.name
  location                                     = var.sql_server_config.location
  resource_group_name                          = var.sql_server_config.resource_group_name
  server_version                               = var.sql_server_config.server_version
  administrator_login                          = var.sql_server_config.administrator_login
  administrator_login_password                 = var.sql_server_config.administrator_login_password
  connection_policy                            = var.sql_server_config.connection_policy
  express_vulnerability_assessment_enabled     = var.sql_server_config.express_vulnerability_assessment_enabled
  outbound_network_restriction_enabled         = var.sql_server_config.outbound_network_restriction_enabled
  primary_user_assigned_identity_id            = var.sql_server_config.primary_user_assigned_identity_id
  public_network_access_enabled                = var.sql_server_config.public_network_access_enabled
  tags                                         = var.sql_server_config.tags
  transparent_data_encryption_key_vault_key_id = var.sql_server_config.transparent_data_encryption_key_vault_key_id
  azuread_administrator                        = var.sql_server_config.azuread_administrator
  lock                                         = var.sql_server_config.lock
  role_assignments                             = var.sql_server_config.role_assignments
  diagnostic_settings                          = var.sql_server_config.diagnostic_settings
  managed_identities                           = var.sql_server_config.managed_identities
  private_endpoints                            = var.sql_server_config.private_endpoints
  private_endpoints_manage_dns_zone_group      = var.sql_server_config.private_endpoints_manage_dns_zone_group
  enable_telemetry                             = var.sql_server_config.enable_telemetry
}

module "private_dns_zone" {
  source  = "Azure/avm-res-network-privatednszone/azurerm"
  version = "0.3.3"

  name                       = var.private_dns_zone_config.name
  resource_group_name        = var.private_dns_zone_config.resource_group_name
  tags                       = var.private_dns_zone_config.tags
  soa_record                 = var.private_dns_zone_config.soa_record
  timeouts                   = var.private_dns_zone_config.timeouts
  virtual_network_links      = var.private_dns_zone_config.virtual_network_links
  a_records                  = var.private_dns_zone_config.a_records
  aaaa_records               = var.private_dns_zone_config.aaaa_records
  cname_records              = var.private_dns_zone_config.cname_records
  mx_records                 = var.private_dns_zone_config.mx_records
  ptr_records                = var.private_dns_zone_config.ptr_records
  srv_records                = var.private_dns_zone_config.srv_records
  txt_records                = var.private_dns_zone_config.txt_records
  role_assignments           = var.private_dns_zone_config.role_assignments
  enable_telemetry           = var.private_dns_zone_config.enable_telemetry
}
